### ISSUE TITLE
question about AristoRoBERTa

### ISSUE THREAD

**Issue by lu1on** [INK-USC/SalKG#1]
Hi, is there any released source about the pre-trained AristoRoBERTa model's checkpoint?

**Comment by aarzchan** [comment]
Hi @lu1on! 

Our paper actually doesn't include AristoRoBERTa results on OBQA, since we didn't find improvements when using SalKG to regularize AristoRoBERTa. However, our repo does provide AristoRoBERTa support.

You can download the pre-trained AristoRoBERTa checkpoint [here](https://drive.google.com/file/d/1QV9s76l5ZPZqP-kV9hizCUDlebuPIzGC/view). We obtained the checkpoint from the authors of [HGN](https://github.com/INK-USC/HGN).
